/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [CustID]
      ,[CustFirstName]
      ,[CustMiddleName]
      ,[CustLastName]
      ,[CustAddress]
      ,[CustCity]
      ,[CustZip]
      ,[CustMobile]
      ,[CustEmailID]
      ,[CustLoginUserName]
      ,[CustPassword]
      ,[CustJoinDate]
      ,[CustLastLoginDtae]
      ,[CustActive]
  FROM [eAirline].[dbo].[CustomerMaster]