/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [FlightNo]
      ,[FlightDestinationFrom]
      ,[FlightDestinationTo]
      ,[FlightDate]
      ,[FlightAirplaneID]
      ,[FlightDepartureTime]
      ,[FlightArivalTime]
      ,[FlightDuration]
      ,[FlightFareEconomy]
      ,[FlightEconomySeat]
      ,[FlightFareBusiness]
      ,[FlightBusinessSeat]
      ,[FlightActive]
  FROM [eAirline].[dbo].[FlightMaster]